# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: stable

# 构建通知[变动或失败邮件通知]
notifications:
  email:
    recipients:
      - devops.aaron@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

# 指定缓存模块，可选[缓存可加快编译速度]。
cache:
  directories:
    - node_modules

# 指定博客源码分支，因人而异。[使用独立repo不用设置此项，此处注释]
# branches:
#  only:
#    - blog 

before_install:
  - git config --global user.name "Aaron"
  - git config --global user.email "devops.aaron@gmail.com"
  - npm install -g hexo-cli

# ==================Build Start============= 
install:
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置 git commit 用户信息及邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - cd ./public
  - git init
  - git add .
  - git commit - m "Update blog is automatically built by TravisCI[$TRAVIS_BUILD_NUMBER]"
  # Github Pages
  - git push --force --quiet "https://${GI_TOKEN}@${GI_REF}" master:master 
  # Coding Pages
  - git push --force --quiet "https://sogclub:${CO_TOKEN}@${CO_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --quiet "https://${GI_TOKEN}@${GI_REF}" master:master --tags


  # [停用]替换同目录下的_config.yml文件中gi_token字符串为配置的变量，注意此处sed命令用双引号。
  #- sed -i "s/gi_token/${GI_TOKEN}/g" ./_config.yml
  #- sed -i "s/co_token/${CO_TOKEN}/g" ./_config.yml
  #- hexo deploy
# ==================Build End===============

env:
 global:
   # Github Pages
   - GI_REF: github.com/Devopswalker/devopswalker.github.io.git
   # Coding Pages
   - CO_REF: git.coding.net/sogclub/sogclub.coding.me.git
